name: randomspawn
version: ${project.version}
author: jkm
main: dev.jkm.randomspawn.RandomSpawn
api-version: 1.14

softdepend: [Towny]

commands:
  randomspawn:
    description: Teleports an operator to a random spawn location.
    usage: /randomspawn